services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - secrets-data:/app/user-secrets    # for secrets.json.enc and the secrets master key


  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"    # Selenium WebDriver endpoint
      - "7900:7900"    # noVNC view, optional
    shm_size: "2g"

volumes:
  secrets-data:
