FROM selenium/standalone-chrome:latest

USER root
COPY docker/launch-chrome.sh /home/seluser/launch-chrome.sh
RUN chmod +x /home/seluser/launch-chrome.sh

USER seluser
ENTRYPOINT ["/home/seluser/launch-chrome.sh"]